[package]
name = "litex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
nom = "7.1.1"
unicode-segmentation = "1.9.0"
